;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        overwrite-mode
        paredit-backward-kill-word
        save-some-buffers
        ))

(setq mc/cmds-to-run-once
      '(
        c-electric-lt-gt
        ))
